pipeline 
{
    agent any
    tools 
    {
        nodejs "NodeJS"
    }
    environment
    {
        IMAGE_REPO_NAME="perch-auth-dev"   
        IMAGE_TAG="$BUILD_NUMBER"
        AWS_DEFAULT_REGION="ap-south-1"
	    MICROSERVICE_NAME="auth"
        REPOSITORY_URI="431437364846.dkr.ecr.ap-south-1.amazonaws.com"
        REMOTE_SERVER_IP = '43.204.194.138'
        REMOTE_SERVER_USER = 'ubuntu'
    }
   
    stages 
    {

        stage('AWS ECR - Login') 
        {
            steps
            {
            script
                {
                    sh "aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin ${REPOSITORY_URI}"
                }
                 
            }
        }

        stage('Checkout')
        {
            steps
            {
                git branch: 'dev', credentialsId: 'GitLab', url: 'https://gitlab.com/Gig0ps/auth.git'
            }
        }
        
        stage('Building Image') 
        {
            steps
            {
                script
                {
                    sh 'docker build -t $MICROSERVICE_NAME:$IMAGE_TAG .'
                }
            }
        } 
        
        stage('Pushing to ECR')
        {
            steps
            {  
                script 
                {
                    sh "docker tag ${MICROSERVICE_NAME}:${IMAGE_TAG} ${REPOSITORY_URI}/${IMAGE_REPO_NAME}:$IMAGE_TAG"
                    sh "docker push ${REPOSITORY_URI}/${IMAGE_REPO_NAME}:${IMAGE_TAG}"
                }
            }
        }
        
        stage('Remove Image from Jenkins')
        {
            steps
            {
                script
                {
                    sh "docker rmi ${MICROSERVICE_NAME}:${IMAGE_TAG}"
                    sh "docker rmi ${REPOSITORY_URI}/${IMAGE_REPO_NAME}:${IMAGE_TAG}"
                }
            }
        }
        
        stage('Update Docker Compose') 
        {
            steps 
            {
                script
                {
                    sh  "sed -i 's|${REPOSITORY_URI}/${IMAGE_REPO_NAME}:.*|${REPOSITORY_URI}/${IMAGE_REPO_NAME}:${IMAGE_TAG}|' /var/lib/jenkins/docker-compose.yaml"
                }
            }
        }

        stage('Deploy to EC2') 
        {
            steps 
            {
                script 
                {
                    sshagent(credentials:['Perchdev-Server'])  
                    {
                        sh "ssh -o StrictHostKeyChecking=no $REMOTE_SERVER_USER@$REMOTE_SERVER_IP 'aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $REPOSITORY_URI'"
                        sh "scp -o StrictHostKeyChecking=no /var/lib/jenkins/docker-compose.yaml $REMOTE_SERVER_USER@$REMOTE_SERVER_IP:/home/ubuntu/docker-compose.yaml"
                        sh "ssh -o StrictHostKeyChecking=no $REMOTE_SERVER_USER@$REMOTE_SERVER_IP 'docker compose -f /home/ubuntu/docker-compose.yaml up -d'"
                        sh "ssh -o StrictHostKeyChecking=no $REMOTE_SERVER_USER@$REMOTE_SERVER_IP 'docker image prune -af'"
                    }
                }
            }
        }
        
    } 
    
    post 
    {
        always
        {
            cleanWs()
        }
    }
}
